name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - '_talks/**'
      - 'talkmap.ipynb'

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to latest version

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to latest version
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter pandas requests beautifulsoup4 geopy getorg

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb
      continue-on-error: true  # Continue even if notebook execution fails, for debugging

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if git commit -m "Automated update of talk locations"; then
          echo "Changes committed successfully"
        else
          echo "No changes to commit"
          exit 0  # Exit successfully to avoid failing the job
        fi

    - name: Push changes
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: |
        git push https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/drmuntasir/drmuntasir.github.io.git
